server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: shop-service
  datasource:
    url: jdbc:h2:mem:testdb
    username: myuser
    password: mypassword
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update